def generate_final_recommendation(
    task,
    best_model
):

    return (
        f"For the detected "
        f"{task} task, "
        f"{best_model} is the "
        f"recommended model "
        f"based on the evaluation "
        f"results generated by "
        f"DocuMind."
    )